// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyyixfbeklsznjaidccc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95eWl4ZmJla2xzem5qYWlkY2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTgxMTgsImV4cCI6MjA2MDYzNDExOH0.U-45xhh0fCowtLPySX_7U98uvNn6QdpdZ3loYN5FsHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);